apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "maira-agent.fullname" . }}-config"
  labels:
{{ include "maira-agent.labels" . | indent 4 }}
data:
  clutch-config.yml: |-
    gateway:
      logger:
        pretty: true
        level: DEBUG
      accesslog:
        # log http 5xx errors by default
        status_code_filters:
          # Unknown - http.StatusInternalServerError
          - equals: 2
          # DeadlineExceeded - http.StatusInternalServerError
          - equals: 4
          # Unimplemented - http.StatusNotImplemented
          - equals: 12
          # Unavailable - http.StatusServiceUnavailable
          - equals: 14
      stats:
        flush_interval: 1s
        log_reporter: {}
      timeouts:
        default: 15s
      middleware:
        - name: clutch.middleware.stats
        - name: clutch.middleware.validate
      listener:
        tcp:
          address: 0.0.0.0
          port: 8080
          secure: false
    modules:
      - name: clutch.module.assets
      - name: clutch.module.healthcheck
      - name: clutch.module.resolver
      - name: clutch.module.aws
      - name: maira_io.module.aws
      - name: clutch.module.envoytriage
      - name: clutch.module.k8s
      - name: maira_io.module.k8s
      - name: clutch.module.kinesis
      - name: maira_io.module.kafka
      - name: maira_io.module.http
      - name: maira_io.module.ssh
      - name: maira_io.module.maira
    services:
      - name: clutch.service.aws
        typed_config:
          "@type": types.google.com/clutch.config.service.aws.v1.Config
          regions:
            - us-east-1
            - us-west-2
      - name: maira_io.service.aws
        typed_config:
          "@type": types.google.com/clutch.config.service.aws.v1.Config
          regions:
            - us-east-1
            - us-west-2
      - name: clutch.service.envoyadmin
        typed_config:
          "@type": types.google.com/clutch.config.service.envoyadmin.v1.Config
          secure: false
          default_remote_port: 9876
      - name: clutch.service.k8s
        typed_config:
          "@type": types.google.com/clutch.config.service.k8s.v1.Config
      - name: maira_io.service.k8s
        typed_config:
          "@type": types.google.com/clutch.config.service.k8s.v1.Config
      - name: maira_io.service.kafka
        typed_config:
          "@type": types.google.com/maira_io.config.service.kafka.v1.Config
          clusters:
            cluster1:
              broker_addresses: [localhost:9092]
            default:
              broker_addresses: [localhost:9093,localhost:9094,localhost:9095]
              tls_config:
                cert_file: ./certs/dev/localhost.crt
                key_file: ./certs/dev/localhost.key
                ca_cert: ./certs/dev/CA.crt
                insecure: true
              sasl_config:
                user: user1
                password: password1
      - name: maira_io.service.http
        typed_config:
          "@type": types.google.com/maira_io.config.service.http.v1.Config
          clusters:
            - name: elastic-default
              addresses:
                - "http://localhost:9200"
              request_headers_add:
                "content-type": "application/json"
              service_name: elasticsearch
              tls_config:
                cert_file: ./certs/dev/localhost.crt
                key_file: ./certs/dev/localhost.key
                ca_cert: ./certs/dev/CA.crt
                insecure: false
      - name: maira_io.service.ssh
        typed_config:
          "@type": types.google.com/maira_io.config.service.ssh.v1.Config
          servers:
            - name: host1
              address: ssh:2022
              username: root
              password: screencast
      - name: maira_io.service.maira
        typed_config:
          "@type": types.google.com/maira_io.config.service.maira.v1.Config
          site_manager_address: {{ .Values.maira.siteManagerAddress }}
          site_name: {{ .Values.maira.site }}
          namespace: {{ .Values.maira.namespace }}
          tenant: {{ .Values.maira.tenant }}
          auth_url: https://maira-dev.us.auth0.com/oauth/token
          auth_client_id: {{ .Values.maira.auth_client_id }}
          auth_client_secret: {{ .Values.maira.auth_client_secret }}
          auth_audience: https://api.maira-dev.maira.io/gateway
    resolvers:
      - name: clutch.resolver.aws
      - name: clutch.resolver.k8s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "maira-agent.fullname" . }}-ssh"
  labels:
{{ include "maira-agent.labels" . | indent 4 }}
data:
{{ (.Files.Glob "ssh/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "maira-agent.fullname" . }}-aws"
  labels:
{{ include "maira-agent.labels" . | indent 4 }}
data:
{{ (.Files.Glob "aws/*").AsConfig | indent 2 }}
