{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.scope.singleNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "maira-gateway.fullname" . }}
  labels:
    {{- include "maira-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - '*'
    resources:
    {{- if not .Values.scope.singleNamespace }}
    - namespaces
    {{- end }}
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
  {{- if .Values.rbac.podSecurityPolicies }}
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      {{- toYaml .Values.rbac.podSecurityPolicies | nindent 6 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.scope.singleNamespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "maira-gateway.fullname" . }}
  labels:
    {{- include "maira-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.scope.singleNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "maira-gateway.fullname" . }}
subjects:
  - name: {{ include "maira-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end -}}